[package]
name = "file_storage"
version = "0.2.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "file_storage"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
hc_zome_file_storage_coordinator = { git = "https://github.com/holochain-open-dev/file-storage", branch = "nixify" }
file_storage_integrity = { workspace = true }